IF DB_ID('aggregator') IS NULL CREATE DATABASE aggregator;
GO
USE aggregator;
GO
IF OBJECT_ID('dbo.Accounts','U') IS NULL
CREATE TABLE dbo.Accounts ( Id BIGINT IDENTITY(1,1) PRIMARY KEY, ExternalRef NVARCHAR(100) NOT NULL UNIQUE, Country NVARCHAR(2) NOT NULL, CreatedUtc DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.Merchants','U') IS NULL
CREATE TABLE dbo.Merchants ( Id BIGINT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Mcc NVARCHAR(4) NULL, Country NVARCHAR(2) NULL, CreatedUtc DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.Transactions','U') IS NULL
CREATE TABLE dbo.Transactions ( Id BIGINT IDENTITY(1,1) PRIMARY KEY, AccountId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Accounts(Id), MerchantId BIGINT NULL FOREIGN KEY REFERENCES dbo.Merchants(Id), Amount DECIMAL(18,2) NOT NULL, Currency NVARCHAR(3) NOT NULL, Country NVARCHAR(2) NULL, DeviceId NVARCHAR(80) NULL, CreatedUtc DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), INDEX IX_Tx_Account_CreatedUtc (AccountId, CreatedUtc DESC));
IF OBJECT_ID('dbo.Fraud_FeatureSnapshots','U') IS NULL
CREATE TABLE dbo.Fraud_FeatureSnapshots ( SnapshotId BIGINT IDENTITY(1,1) PRIMARY KEY, TransactionId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Transactions(Id), AccountId BIGINT NOT NULL, FeaturesJson NVARCHAR(MAX) NOT NULL, CreatedUtc DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.Fraud_Scores','U') IS NULL
CREATE TABLE dbo.Fraud_Scores ( TransactionId BIGINT PRIMARY KEY FOREIGN KEY REFERENCES dbo.Transactions(Id), ModelVersion NVARCHAR(64) NOT NULL, Score FLOAT NOT NULL, ReasonCodes NVARCHAR(MAX) NOT NULL, CreatedUtc DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.Fraud_Decisions','U') IS NULL
CREATE TABLE dbo.Fraud_Decisions ( TransactionId BIGINT PRIMARY KEY FOREIGN KEY REFERENCES dbo.Transactions(Id), Decision NVARCHAR(16) NOT NULL CHECK (Decision IN ('allow','hold','block','review')), ThresholdUsed FLOAT NOT NULL, AnalystId BIGINT NULL, Notes NVARCHAR(4000) NULL, CreatedUtc DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
GO
